In [474]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [475]:
from sklearn import linear_model, metrics

In [476]:
import decimal
from decimal import Decimal
import math
import random
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.kernel_ridge import KernelRidge
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
np.set_printoptions(suppress=True)
mydf=pd.read_csv('GNPStrainqed',  sep='\t')
mydf.columns=['smiles','mz','mw','alogp','hba','hbd', 'psa', 'rotb', 'arom', 'alerts', 'qed', 'fCSP3', 'logPow', 'solubility', 'bioavailability']

#mydf.columns=['molecule number', 'FDA approved name', 'mz', 'smiles', 'mw', 'alogp', 'hba', 'hbd', 'psa', 'rotb', 'arom', 'alerts', 'qed', 'fraction sp3 hybridized carbons']

# Initialize lists and set random seed
print(mydf)
list_x = mydf['mz']

list_x=list_x.astype(float)
list_x=list_x.to_numpy().reshape(-1,1)
list_y = mydf['qed'].to_numpy().reshape(-1,1)
list_x_pred = []
list_y_real = []

np.set_printoptions(precision = 5, suppress = True)

list_y = np.nan_to_num(list_y)

list_x = np.nan_to_num(list_x)

        
list_y=pd.DataFrame(list_y)
list_y.to_csv('myyvalues.csv')
print(list_y.mean())
print(list_y.std())

                                                        smiles       mz  \
CC(C)CC1NC(=O)C(C)NC(=O)C(=C)N(C)C(=O)CCC(NC(=O...  289.286377  981.162   
NaN                                                 295.545288  981.162   
NaN                                                 298.489624  981.162   
NaN                                                 317.324951  981.162   
NaN                                                 319.655945  981.162   
...                                                        ...      ...   
NaN                                                 998.175903  786.689   
NaN                                                 998.381592  786.689   
NaN                                                 998.490723  786.689   
NaN                                                 998.799988  786.689   
NaN                                                 999.381165  786.689   

                                                         mw  alogp   hba  \
CC(C)CC1NC(=O)C(C)NC(=O

In [477]:
import numpy as np
from sklearn.kernel_ridge import KernelRidge
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt


In [480]:
# ####################
# Fit regression model
train_size = 100 # Change here to try different amounts of data
krr = GridSearchCV(KernelRidge(kernel='rbf',alpha=100),
                  param_grid={"gamma": np.logspace(-400, 400, 2)})

krr.fit(list_x[:train_size], list_y[:train_size])

print('Best gamma from CV: ',krr.best_params_)
print('Length scale =',1/np.sqrt(2*krr.best_params_['gamma']))
krr.score(list_x, list_y )

ValueError: array must not contain infs or NaNs

In [481]:
from sklearn.datasets import make_regression
from matplotlib import pyplot as plt
import numpy as np
from sklearn.linear_model import Ridge


X_plot = np.linspace(0, 10, 1000)[:, None]
scaler = preprocessing.StandardScaler()
list_x = scaler.fit_transform(list_x)
list_y = scaler.fit_transform(list_y)


In [482]:
xtrain, xtest, ytrain, ytest=train_test_split(list_x, list_y, test_size=0.15)

In [483]:
import numpy as np
import pandas as pd

# For chapter 4
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# For chapter 5
from sklearn.linear_model import SGDClassifier
import matplotlib.pyplot as plt
import time

# For chapter 6
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV



In [484]:
scaler = StandardScaler()
scaler.fit(xtrain)
xtrain = scaler.transform(xtrain)
xtest = scaler.transform(xtest)

trainX, testX, trainY, testY = train_test_split(xtrain, ytrain, test_size = 0.2)
testY

array([[-0.1519 ],
       [-0.11815],
       [-0.11815],
       ...,
       [-0.00423],
       [-0.11815],
       [-0.11815]])

In [485]:
scaler = StandardScaler()
scaler.fit(trainX)
trainX = scaler.transform(trainX)
testX = scaler.transform(testX)


In [486]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler


In [487]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler

from sklearn import linear_model
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

import warnings

In [488]:
warnings.filterwarnings('ignore')

In [489]:


%matplotlib inline

plt.rcParams['figure.figsize'] = [20.0, 7.0]
plt.rcParams.update({'font.size': 22,})

sns.set_palette('viridis')
sns.set_style('white')
sns.set_context('talk', font_scale=0.8)
 


In [490]:
X_plot = np.linspace(0, 10, 1000)[:, None]
scaler = preprocessing.StandardScaler()
list_x = scaler.fit_transform(list_x)
list_y = np.nan_to_num(list_y)

list_x = np.nan_to_num(list_x)

list_y=np.asarray(list_y)

list_y=list_y.reshape(1, -1)
list_y = scaler.fit_transform(list_y)
list_y
n_samples, n_features = 1, 5
#krr = KernelRidge(alpha=5)
#krr.fit(list_x, list_y)
#predy=krr.predict(list_x)
#krr.score(list_y, predy )
ridge = linear_model.Ridge(alpha=.1)
lasso = linear_model.Lasso(alpha=1, normalize=True, max_iter = 100000)

# ####################
# Fit regression model
from sklearn.linear_model import LassoCV

#Lasso Cross validation
lasso_cv = LassoCV(alphas = [0.0001, 0.001,0.01, 0.1, 1, 10], random_state=0).fit(trainX, trainY)


#score
print(lasso_cv.score(trainX, trainY))
print(lasso_cv.score(testX, testY))


elastic = linear_model.ElasticNet()
lasso_lars = linear_model.LassoLars()
bayesian_ridge = linear_model.BayesianRidge()
logistic = linear_model.LogisticRegression(solver='liblinear')
sgd = linear_model.SGDRegressor()

models = [ridge, lasso, elastic, lasso_lars, bayesian_ridge, logistic, sgd]



0.0
-9.765694123586854e-06


In [491]:
trainX.reshape(1, -1)
trainY.reshape(1,-1)
ridge.fit(trainX, trainY)
lasso.fit(trainX, trainY)
elastic.fit(trainX, trainY)
lasso_lars.fit(trainX, trainY)
bayesian_ridge.fit(trainX, trainY)
sgd.fit(trainX,trainY)

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [492]:
ypredridge=ridge.predict(testX)
ypredlasso=lasso.predict(testX)
ypredelastic=elastic.predict(testX)
ypredlassolars = lasso_lars.predict(testX)
ypredbayesian=bayesian_ridge.predict(testX)
sgdpredict=sgd.predict(testX)

In [493]:
testY[~np.isfinite(testY)] = 0
ypredridge[~np.isfinite(ypredridge)] = 0

sgdscore = sgd.score(testY, ypredridge)
print("R-squared:", sgdscore)

R-squared: -38.53294434763176


In [494]:

score = bayesian_ridge.score(testY, ypredridge)
print("R-squared:", score)

R-squared: -0.6994269048320181


In [495]:
yx=lasso_lars.score(testY, ypredlassolars)

from sklearn.metrics import mean_squared_error

mean_squared_error(testY, ypredlassolars)

#z = (x - u) / s
#where u is mean and s is standard dev
#x=  375.801398

#std is    151.243536
mean_squared_error


<function sklearn.metrics.regression.mean_squared_error(y_true, y_pred, sample_weight=None, multioutput='uniform_average')>

In [496]:
elastic.score(testY, ypredelastic)

1.0

In [497]:
lasso.score(testY, ypredlasso)



1.0

In [498]:
ridge.score(testY, ypredridge)

-1.1856518013215727

In [499]:
trainX

array([[-0.3215 ],
       [-0.35384],
       [-0.61269],
       ...,
       [-0.61269],
       [-0.61269],
       [ 0.62077]])

In [500]:
testY

array([[-0.1519 ],
       [-0.11815],
       [-0.11815],
       ...,
       [-0.00423],
       [-0.11815],
       [-0.11815]])

In [501]:
ypred=lasso.predict(testX)

#z = (x - u) / s
#where u is mean and s is standard dev


print( "Predicted values ", np.round( ypred[:10], 10 ) ) 



Predicted values  [-0.00101 -0.00101 -0.00101 -0.00101 -0.00101 -0.00101 -0.00101 -0.00101
 -0.00101 -0.00101]


In [502]:
df_preds = pd.DataFrame({'Actual': testY.squeeze(), 'Predicted': ypred.squeeze()})
print(df_preds)

          Actual  Predicted
0      -0.151905  -0.001005
1      -0.118151  -0.001005
2      -0.118151  -0.001005
3       0.185631  -0.001005
4       0.177192  -0.001005
...          ...        ...
169624  0.113904  -0.001005
169625 -0.118151  -0.001005
169626 -0.004233  -0.001005
169627 -0.118151  -0.001005
169628 -0.118151  -0.001005

[169629 rows x 2 columns]


In [503]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
mae = mean_absolute_error(testY, ypred)
mse = mean_squared_error(testY, ypred)
rmse = np.sqrt(mse)
print(f'Mean absolute error: {mae:.14f}')
print(f'Mean squared error: {mse:.14f}')
print(f'Root mean squared error: {rmse:.5f}')

Mean absolute error: 0.14538389021970
Mean squared error: 1.18200287337445
Root mean squared error: 1.08720


In [1401]:
mydf=pd.read_csv('compound210',  sep='\t')
mydf.columns=['mz','qed']
#mydf.columns=['molecule number', 'FDA approved name', 'mz', 'smiles', 'mw', 'alogp', 'hba', 'hbd', 'psa', 'rotb', 'arom', 'alerts', 'qed', 'fraction sp3 hybridized carbons']

# Initialize lists and set random seed
print(mydf)
list_x = mydf['mz']

list_x=list_x.astype(float)
list_x=list_x.to_numpy().reshape(-1,1)
list_y = mydf['qed'].to_numpy().reshape(-1,1)
list_x_pred = []
list_y_real = []

np.set_printoptions(precision = 5, suppress = True)

list_ya = np.nan_to_num(list_y)

list_xa = np.nan_to_num(list_x)

        
list_y=pd.DataFrame(list_y)

ymean=list_y.mean()
ystd=list_y.std()

          mz       qed
0   161.2000  0.167133
1   162.1000  0.167133
2   163.4000  0.167133
3   186.1000  0.167133
4   203.0000  0.167133
5   205.5000  0.167133
6   233.4000  0.167133
7   234.4000  0.167133
8   235.4000  0.167133
9   243.2000  0.167133
10  280.5000  0.167133
11  323.8000  0.167133
12  324.7000  0.167133
13  351.5000  0.167133
14  365.5000  0.167133
15  449.4000  0.167133
16  467.3000  0.167133
17  484.6000  0.167133
18  138.0913  0.167133


In [1402]:

scaler = preprocessing.StandardScaler()
list_x = scaler.fit_transform(list_xa)
list_y = scaler.fit_transform(list_ya)


In [1403]:
#ypredridge=ridge.predict(testX)
ypredlasso=lasso.predict(list_x)

In [1404]:
ypredlasso

array([-0.00101, -0.00101, -0.00101, -0.00101, -0.00101, -0.00101,
       -0.00101, -0.00101, -0.00101, -0.00101, -0.00101, -0.00101,
       -0.00101, -0.00101, -0.00101, -0.00101, -0.00101, -0.00101,
       -0.00101])

In [1405]:
df_preds = pd.DataFrame({'Actual': list_y.squeeze(), 'Predicted': ypredlasso.squeeze()})
print(df_preds)

    Actual  Predicted
0      1.0  -0.001005
1      1.0  -0.001005
2      1.0  -0.001005
3      1.0  -0.001005
4      1.0  -0.001005
5      1.0  -0.001005
6      1.0  -0.001005
7      1.0  -0.001005
8      1.0  -0.001005
9      1.0  -0.001005
10     1.0  -0.001005
11     1.0  -0.001005
12     1.0  -0.001005
13     1.0  -0.001005
14     1.0  -0.001005
15     1.0  -0.001005
16     1.0  -0.001005
17     1.0  -0.001005
18     1.0  -0.001005


In [1406]:
#z = (x - u) / s
#where u is mean and s is standard dev
myval=ypredlasso[0] * ystd + ymean

print(myval)

0    0.167133
dtype: float64


In [1346]:


.000815 * 5.681747e-17 + 0.149406

0.149406

In [103]:
list_y.std()

0.0

In [104]:
list_y.columns=['qed']

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [38]:
list_y['qed']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [31]:
print("std of arr : ", np.std(list_y['qed']))
  

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [1407]:
mydf=pd.read_csv('GNPStrainqed',  sep='\t')