In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [2]:
from sklearn import linear_model, metrics

In [118]:
import decimal
from decimal import Decimal
import math
import random
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.kernel_ridge import KernelRidge
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
np.set_printoptions(suppress=True)
mydf=pd.read_csv('GNPStrainqed.csv',  sep=',')
mydf.columns=['','mz','mw','alogp','hba','hbd','psa','rotb','arom','alerts','qed','pains','fsp3','cacao','halflife','logs','logd','bioconcen','igc50','lc50fm','lc50dm']

#mydf.columns=['molecule number', 'FDA approved name', 'mz', 'smiles', 'mw', 'alogp', 'hba', 'hbd', 'psa', 'rotb', 'arom', 'alerts', 'qed', 'fraction sp3 hybridized carbons']

# Initialize lists and set random seed
print(mydf)
list_x = mydf['mz']

list_x=list_x.astype(float)
list_x=list_x.to_numpy().reshape(-1,1)
list_y = mydf['bioconcen'].to_numpy().reshape(-1,1)
print(list_y)
list_x_pred = []
list_y_real = []

np.set_printoptions(precision = 5, suppress = True)

list_y = np.nan_to_num(list_y)

list_x = np.nan_to_num(list_x)

        
list_y=pd.DataFrame(list_y)



                    mz       mw    alogp    hba  hbd     psa  rotb  arom  \
0      NaN  289.286377  981.162  0.17397     14   12  351.64    14     1   
1      NaN  295.545288  981.162  0.17397     14   12  351.64    14     1   
2      NaN  298.489624  981.162  0.17397     14   12  351.64    14     1   
3      NaN  317.324951  981.162  0.17397     14   12  351.64    14     1   
4      NaN  319.655945  981.162  0.17397     14   12  351.64    14     1   
...    ...         ...      ...      ...    ...  ...     ...   ...   ...   
71130  NaN  167.000000  180.156 -3.22140  29404    5  110.38     1     0   
71131  NaN  167.500000  180.156 -3.22140  29405    5  110.38     1     0   
71132  NaN  167.750000  180.156 -3.22140  29406    5  110.38     1     0   
71133  NaN  168.083344  180.156 -3.22140  29407    5  110.38     1     0   
71134  NaN  168.583344  180.156 -3.22140  29408    5  110.38     1     0   

       alerts  ...  pains   fsp3  cacao  halflife   logs   logd  bioconcen  \
0        

In [67]:
import numpy as np
from sklearn.kernel_ridge import KernelRidge
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt


In [68]:
# ####################
# Fit regression model
train_size = 100 # Change here to try different amounts of data
krr = GridSearchCV(KernelRidge(kernel='rbf',alpha=100),
                  param_grid={"gamma": np.logspace(-400, 400, 2)})

krr.fit(list_x[:train_size], list_y[:train_size])

print('Best gamma from CV: ',krr.best_params_)
print('Length scale =',1/np.sqrt(2*krr.best_params_['gamma']))
krr.score(list_x, list_y )

Best gamma from CV:  {'gamma': 0.0}
Length scale = inf


/home/patrickchirdon/Documents/biosortia-lipinski/biosortia/lib/python3.10/site-packages/numpy/core/function_base.py:284: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)
/home/patrickchirdon/Documents/biosortia-lipinski/biosortia/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
5 fits failed out of a total of 10.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/patrickchirdon/Documents/biosortia-lipinski/biosortia/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/patrickchi

-0.012176237643916732

In [69]:
from sklearn.datasets import make_regression
from matplotlib import pyplot as plt
import numpy as np
from sklearn.linear_model import Ridge


X_plot = np.linspace(0, 10, 1000)[:, None]
scaler = preprocessing.StandardScaler()
list_x = scaler.fit_transform(list_x)
list_y = scaler.fit_transform(list_y)


In [70]:
xtrain, xtest, ytrain, ytest=train_test_split(list_x, list_y, test_size=0.15)

In [71]:
import numpy as np
import pandas as pd

# For chapter 4
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# For chapter 5
from sklearn.linear_model import SGDClassifier
import matplotlib.pyplot as plt
import time

# For chapter 6
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV



In [72]:
scaler = StandardScaler()
scaler.fit(xtrain)
xtrain = scaler.transform(xtrain)
xtest = scaler.transform(xtest)

trainX, testX, trainY, testY = train_test_split(xtrain, ytrain, test_size = 0.2)



In [73]:
scaler = StandardScaler()
scaler.fit(trainX)
trainX = scaler.transform(trainX)
testX = scaler.transform(testX)


In [74]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler


In [75]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler

from sklearn import linear_model
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

import warnings

ModuleNotFoundError: No module named 'seaborn'

In [76]:
warnings.filterwarnings('ignore')

NameError: name 'warnings' is not defined

In [77]:


%matplotlib inline

plt.rcParams['figure.figsize'] = [20.0, 7.0]
plt.rcParams.update({'font.size': 22,})

sns.set_palette('viridis')
sns.set_style('white')
sns.set_context('talk', font_scale=0.8)
 


NameError: name 'sns' is not defined

In [78]:
X_plot = np.linspace(0, 10, 1000)[:, None]
scaler = preprocessing.StandardScaler()
list_x = scaler.fit_transform(list_x)
list_y = np.nan_to_num(list_y)

list_x = np.nan_to_num(list_x)

list_y=np.asarray(list_y)

list_y=list_y.reshape(1, -1)
list_y = scaler.fit_transform(list_y)
list_y
n_samples, n_features = 1, 5
#krr = KernelRidge(alpha=5)
#krr.fit(list_x, list_y)
#predy=krr.predict(list_x)
#krr.score(list_y, predy )
ridge = linear_model.Ridge(alpha=.1)
lasso = linear_model.Lasso(alpha=1, max_iter = 100000)

# ####################
# Fit regression model
from sklearn.linear_model import LassoCV

#Lasso Cross validation
lasso_cv = LassoCV(alphas = [0.0001, 0.001,0.01, 0.1, 1, 10], random_state=0).fit(trainX, trainY)


#score
print(lasso_cv.score(trainX, trainY))
print(lasso_cv.score(testX, testY))


elastic = linear_model.ElasticNet()
lasso_lars = linear_model.LassoLars()
bayesian_ridge = linear_model.BayesianRidge()
logistic = linear_model.LogisticRegression(solver='liblinear')
sgd = linear_model.SGDRegressor()

models = [ridge, lasso, elastic, lasso_lars, bayesian_ridge, logistic, sgd]



0.0069671701693875265
0.0064411590850316225


/home/patrickchirdon/Documents/biosortia-lipinski/biosortia/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:1561: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [79]:
trainX.reshape(1, -1)
trainY.reshape(1,-1)
ridge.fit(trainX, trainY)
lasso.fit(trainX, trainY)
elastic.fit(trainX, trainY)
lasso_lars.fit(trainX, trainY)
bayesian_ridge.fit(trainX, trainY)
sgd.fit(trainX,trainY)

/home/patrickchirdon/Documents/biosortia-lipinski/biosortia/lib/python3.10/site-packages/sklearn/utils/validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/patrickchirdon/Documents/biosortia-lipinski/biosortia/lib/python3.10/site-packages/sklearn/utils/validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor()

In [80]:
ypredridge=ridge.predict(testX)
ypredlasso=lasso.predict(testX)
ypredelastic=elastic.predict(testX)
ypredlassolars = lasso_lars.predict(testX)
ypredbayesian=bayesian_ridge.predict(testX)
sgdpredict=sgd.predict(testX)

In [81]:
#testY[~np.isfinite(testY)] = 0
#testY[~np.isnan(testY)]=0
ypredlasso[~np.isfinite(ypredlasso)] = 0

lassoscore = lasso.score(testY, ypredlasso)
print("R-squared:", lassoscore)

R-squared: 1.0


In [82]:

score = bayesian_ridge.score(testY, ypredridge)
print("R-squared:", score)

R-squared: -0.7702113518217613


In [83]:
yx=lasso_lars.score(testY, ypredlassolars)

from sklearn.metrics import mean_squared_error

mean_squared_error(testY, ypredlassolars)

#z = (x - u) / s
#where u is mean and s is standard dev
#x=  375.801398

#std is    151.243536
mean_squared_error


<function sklearn.metrics._regression.mean_squared_error(y_true, y_pred, *, sample_weight=None, multioutput='uniform_average', squared=True)>

In [84]:
elastic.score(testY, ypredelastic)

1.0

In [85]:
lasso.score(testY, ypredlasso)



1.0

In [86]:
ridge.score(testY, ypredridge)

-0.7752283560685156

In [87]:
trainX

array([[ 3.57083],
       [-1.22735],
       [ 1.66544],
       ...,
       [ 0.03596],
       [-1.00314],
       [ 1.56236]])

In [88]:
testY

array([[-0.17885],
       [-0.17885],
       [-0.18726],
       ...,
       [-0.14981],
       [-0.14847],
       [-0.15574]])

In [89]:
ypred=lasso.predict(testX)

#z = (x - u) / s
#where u is mean and s is standard dev


print( "Predicted values ", np.round( ypred[:10], 10 ) ) 



Predicted values  [0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001 0.00001
 0.00001]


In [90]:
df_preds = pd.DataFrame({'Actual': testY.squeeze(), 'Predicted': ypred.squeeze()})
print(df_preds)

         Actual  Predicted
0     -0.178852   0.000008
1     -0.178852   0.000008
2     -0.187258   0.000008
3     -0.142876   0.000008
4     -0.190326   0.000008
...         ...        ...
12088 -0.165907   0.000008
12089 -0.202094   0.000008
12090 -0.149811   0.000008
12091 -0.148466   0.000008
12092 -0.155737   0.000008

[12093 rows x 2 columns]


In [91]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
mae = mean_absolute_error(testY, ypred)
mse = mean_squared_error(testY, ypred)
rmse = np.sqrt(mse)
print(f'Mean absolute error: {mae:.14f}')
print(f'Mean squared error: {mse:.14f}')
print(f'Root mean squared error: {rmse:.5f}')

Mean absolute error: 0.32300564615921
Mean squared error: 0.92476286335726
Root mean squared error: 0.96165


In [120]:
mydf=pd.read_csv('Boscalid.csv',  sep=',')
mydf.columns=['mz', 'pains', 'fsp3', 'cacao', 'halflife', 'logs', 'logd', 'bioconcentration', 'igc50', 'lc50fm', 'lc50dm']
#mydf.columns=['molecule number', 'FDA approved name', 'mz', 'smiles', 'mw', 'alogp', 'hba', 'hbd', 'psa', 'rotb', 'arom', 'alerts', 'qed', 'fraction sp3 hybridized carbons']

# Initialize lists and set random seed
print(mydf)
list_x = mydf['mz']

list_x=list_x.astype(float)
list_x=list_x.to_numpy().reshape(-1,1)
list_y = mydf['bioconcentration'].to_numpy().reshape(-1,1)
list_x_pred = []
list_y_real = []

np.set_printoptions(precision = 5, suppress = True)

list_ya = np.nan_to_num(list_y)

list_xa = np.nan_to_num(list_x)

        
list_y=pd.DataFrame(list_y)

ymean=list_y.mean()
ystd=list_y.std()
ystd

            mz  pains  fsp3  cacao  halflife   logs   logd  bioconcentration  \
0    93.773705      0     0 -4.689     0.116 -5.307  3.477             2.277   
1   147.951980      0     0 -4.689     0.116 -5.307  3.477             2.277   
2   148.747986      0     0 -4.689     0.116 -5.307  3.477             2.277   
3   148.960230      0     0 -4.689     0.116 -5.307  3.477             2.277   
4   149.058540      0     0 -4.689     0.116 -5.307  3.477             2.277   
5   149.309520      0     0 -4.689     0.116 -5.307  3.477             2.277   
6   149.491130      0     0 -4.689     0.116 -5.307  3.477             2.277   
7   154.200317      0     0 -4.689     0.116 -5.307  3.477             2.277   
8   165.050537      0     0 -4.689     0.116 -5.307  3.477             2.277   
9   189.064650      0     0 -4.689     0.116 -5.307  3.477             2.277   
10  204.141030      0     0 -4.689     0.116 -5.307  3.477             2.277   
11  310.129480      0     0 -4.689     0

0    0.0
dtype: float64

In [121]:

scaler = preprocessing.StandardScaler()
list_x = scaler.fit_transform(list_xa)
list_y = scaler.fit_transform(list_ya)


ypredridge=ridge.predict(list_x)
ypredlasso=elastic.predict(list_x)

ypredelastic=elastic.predict(list_x)
ypredlassolars = lasso_lars.predict(list_x)
ypredbayesian=bayesian_ridge.predict(list_x)
sgdpredict=sgd.predict(list_x)

yhat = scaler.inverse_transform(ypredridge)
df_preds = pd.DataFrame({'Actual': list_y.squeeze(), 'Predicted': ypredlasso.squeeze()})
print(df_preds)

    Actual  Predicted
0      0.0   0.000008
1      0.0   0.000008
2      0.0   0.000008
3      0.0   0.000008
4      0.0   0.000008
5      0.0   0.000008
6      0.0   0.000008
7      0.0   0.000008
8      0.0   0.000008
9      0.0   0.000008
10     0.0   0.000008
11     0.0   0.000008
12     0.0   0.000008
13     0.0   0.000008
14     0.0   0.000008
15     0.0   0.000008


In [122]:
#ypredridge=ridge.predict(testX)
ypredlasso=lasso.predict(list_x)

In [123]:
ypredlasso

array([0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001,
       0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001, 0.00001,
       0.00001, 0.00001])

In [125]:
ystd=testY.std()
ymean=testY.mean()
print(ymean)

-0.010310433521434192


In [111]:
#z = (x - u) / s
#where u is mean and s is standard dev
myval=ypredlasso[0] * ystd + ymean

print(myval)
print(ystd)

0   -5.306992
dtype: float64
0.9615905499019554


In [674]:


.000815 * 5.681747e-17 + 0.149406

0.149406

In [675]:
list_y.std()

0.0

In [676]:
list_y.columns=['qed']

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [677]:
list_y['qed']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [678]:
print("std of arr : ", np.std(list_y['qed']))
  

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [679]:
mydf=pd.read_csv('GNPStrainqed',  sep='\t')

/tmp/ipykernel_35081/3908447724.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  mydf=pd.read_csv('GNPStrainqed',  sep='\t')


In [525]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import ReduceLROnPlateau
from keras import regularizers as WeightRegularizer
from keras.optimizers import SGD
    #SKlearn for metrics and datasplits
from sklearn.model_selection import cross_validate
from sklearn.metrics import roc_auc_score, roc_curve
    #Matplotlib for plotting
from matplotlib import pyplot as plt
from keras.regularizers import l2

    # In[11]:


    #Convert to Numpy arrays
from sklearn.preprocessing import StandardScaler
X = np.array(list(list_x))
y = pd.read_csv('myval.csv', sep=',')
y=y.iloc[:, 1]


from keras import backend as K

def r2_score(y_test, y_pred):
    SS_res =  K.sum(K.square( y_test-y_pred )) 
    SS_tot = K.sum(K.square( y_test - K.mean(y_test) ) ) 
    return ( 1 - SS_res/(SS_tot + K.epsilon()) )



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

model = Sequential()
model.add(Dense(600, input_dim=X.shape[1], activation='relu'))
model.add(Dropout(0.6, input_shape=(1,)))
model.add(Dense(600, input_dim=X.shape[1], activation='relu'))
model.add(Dropout(0.6, input_shape=(1,)))
model.add(Dense(6, activation='sigmoid'))
    # In[34]:

model.compile(loss='mean_squared_error',
              optimizer='adam' , metrics = ['mae', 'mse', r2_score])
model.fit(X_train, y_train, epochs=1, batch_size=2)
    
    
y_pred = model.predict(X_test)

   

ValueError: Found input variables with inconsistent numbers of samples: [51, 71135]

In [ ]:
y_train.size

In [ ]:
X_train.size

In [344]:
X.size

51

In [345]:
y.size

71135

In [346]:
X[1]

array([-1.54052])

In [227]:
y[1]

0.0

In [228]:
y_test.size

14227

In [229]:
y_pred.size


85362

In [230]:
y.size

71135